name: Continuous integration example - Multiple jobs

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from job2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from job3"